apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ut5s
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-ut5s@sha256:68a7d2798ee97f57fc3d311b2ab2ab7814a08e33b8fb7f2f0209dce75dfe63cf
        name: my-nodejs
        resources: {}
status: {}
